include:
  - ./indexer/docker-compose.yml

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - app-network
    env_file:
      - ./frontend/.env
    environment:
      - VITE_GRAPH_QL_ENDPOINT=http://localhost:5100/graphql
    restart: always
    depends_on:
      indexer:
        condition: service_healthy
