scalar BigDecimalU256

type Deposit {
  id: ID!
  commitment: BigDecimalU256!
  leaf_index: Int!
  timestamp: Int!
  block_number: Int!
  tx_hash: String!
}

type Withdrawal {
  id: ID!
  recipient: String!
  nullifier_hash: BigDecimalU256!
  block_number: Int!
  tx_hash: String!
}

type WbtcOrder {
  id: ID!
  wbtc_seller: String!
  alice_strk_destination: String!
  wbtc_amount: BigDecimalU256!
  quoted_strk_amount: BigDecimalU256!
  hashlock: String!
  expiry: Int!
  rate_expiry: Int!
  wbtc_buyer: String
  strk_order_id: String
  strk_amount_locked: BigDecimalU256
  bob_expiry: Int
  is_filled: Boolean!
  is_withdrawn: Boolean!
  is_refunded: Boolean!
  posted_at_block: Int!
  posted_tx_hash: String!
  filled_at_block: Int
  withdrawn_at_block: Int
  refunded_at_block: Int
}

type StrkOrder {
  id: ID!
  strk_seller: String!
  strk_buyer: String!
  strk_amount: BigDecimalU256!
  hashlock: String!
  expiry: Int!
  wbtc_order_id: String
  is_withdrawn: Boolean!
  is_refunded: Boolean!
  posted_at_block: Int!
  posted_tx_hash: String!
  withdrawn_at_block: Int
  refunded_at_block: Int
}

type OwnershipTransfer {
  id: ID!
  previous_owner: String!
  new_owner: String!
  block_number: Int!
  tx_hash: String!
}
